### ISSUE TITLE
How to speedup the process of quantization which takes almost 20 hours to quantize llama3-70B with w8a8

### ISSUE THREAD

**Issue by moonlightian** [vllm-project/llm-compressor#968] opened 2024-12-11 02:33 UTC
llmcompressor==0.2.0
compressed-tensors==0.7.1
4  NVIDIA A100 80GB PCIe
```
from transformers import AutoModelForCausalLM, AutoTokenizer
MODEL_ID = "/llama3_1_70B"
model = SparseAutoModelForCausalLM.from_pretrained(
MODEL_ID, device_map="auto", torch_dtype="auto",
)
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
NUM_CALIBRATION_SAMPLES = 512
MAX_SEQUENCE_LENGTH = 2048
ds = ds.shuffle(seed=42).select(range(NUM_CALIBRATION_SAMPLES))

def preprocess(example):
    return {"text": tokenizer.apply_chat_template(example["text"], tokenize=False)}
ds = ds.map(preprocess)

def tokenize(sample):
    return tokenizer("\n\n".join(sample['text']), return_tensors='pt')
ds = ds.map(tokenize, remove_columns=ds.column_names)

from llmcompressor.transformers import oneshot
from llmcompressor.modifiers.quantization import GPTQModifier
from llmcompressor.modifiers.smoothquant import SmoothQuantModifier

# Configure the quantization algorithms
recipe = [
    SmoothQuantModifier(smoothing_strength=0.8),
    GPTQModifier(targets="Linear", dampening_frac=0.1, scheme="W8A8", ignore=["lm_head"]),
]

# Apply quantization
oneshot(
    model=model,
    dataset=ds,
    recipe=recipe,
    max_seq_length=MAX_SEQUENCE_LENGTH,
    num_calibration_samples=NUM_CALIBRATION_SAMPLES,
)
```

**Comment by dsikka** [comment] 2024-12-14 13:28
Hi @moonlightian:
1. Can you confirm you ran the above with 4 x A100s?
2. Can you also confirm the stub of the model that was used and the dataset name? I had some trouble processing the dataset list with the preprocess functions provided.

**Comment by ehartford** [comment] 2024-12-17 01:02
are we supposed to run it with `accelerate launch`
mine only uses 1 gpu at a time (but it keeps cycling through the GPUs)

**Comment by dsikka** [comment] 2024-12-17 01:09
@ehartford accelerate is required to be installed however, you do not have to run anything beyond calling oneshot

**Comment by ehartford** [comment] 2024-12-17 01:18
Then I must report experiencing the same issue - it is very very slow and only utilizing 1 out of my 8 GPUs

**Comment by dsikka** [comment] 2024-12-17 01:38
@ehartford Can you confirm you're on latest llmcompressor/compressed-tensors and share the code you're running? With multiple gpus, setting `device_map="auto"` should use more than 1 GPU, if they're available.

**Comment by ehartford** [comment] 2024-12-17 03:14
yes latest

I just use 

https://github.com/vllm-project/llm-compressor/blob/main/examples/quantizing_moe/deepseek_moe_w8a8_fp8.py

I make this change so it will do cpu offload:

```
...
from llmcompressor.transformers.compression.helpers import calculate_offload_device_map

# select a Mixture of Experts model for quantization
MODEL_ID = "/home/ubuntu/models/DeepSeek-V2.5-1210"

device_map = calculate_offload_device_map(
    MODEL_ID,
    reserve_for_hessians=True,
    num_gpus=8,
    torch_dtype=torch.bfloat16,
    trust_remote_code=True,
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID, device_map=device_map, torch_dtype="auto", trust_remote_code=True
)
```

**Comment by ehartford** [comment] 2024-12-17 03:36
![image](https://github.com/user-attachments/assets/4bcdfb89-739d-4acd-b11a-a1e432f4777b)

**Comment by dsikka** [comment] 2024-12-17 14:03
Hi @moonlightian 
We ran the experiment on our end with both 4 x A100 and 1 x A100.
With 4 x A100, we expect about 6-7 hours of time.
With 1 x A100, we expect about 12-13 hours.

Can you try updating to the latest compressed-tensors/llmcompressor and ensure accelerate is installed?
After that, can you try passing in the following device_map, when loading the model?

```python
from llmcompressor.transformers.compression.helpers import calculate_offload_device_map
device_map = calculate_offload_device_map(
    MODEL_ID, num_gpus=n_gpus, reserve_for_hessians=True, torch_dtype="auto"
)
```

Once the model is loaded, can you confirm what the following output looks like?
```
for m in model.model.layers:
    print(m.self_attn.q_proj.weight.device)
```

**Comment by dsikka** [comment] 2024-12-17 14:06
> 88 hours to convert it to fp8 - and only using a tiny portion of my GPU compute
> 
> ![image](https://private-user-images.githubusercontent.com/1117701/396341437-4bcdfb89-739d-4acd-b11a-a1e432f4777b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDQyNTgsIm5iZiI6MTczNDQ0Mzk1OCwicGF0aCI6Ii8xMTE3NzAxLzM5NjM0MTQzNy00YmNkZmI4OS03MzlkLTRhY2QtYjExYS1hMWU0MzJmNDc3N2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTdUMTM1OTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjYzMDZjOTcyMWZlODAyODQ5MGQ2M2NiZjNmMWM1N2Y5OTZkMDBlM2U0NjU3OGJjMDI0MWVkMTBiNmU5N2VhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.arFF5hm40F3bBcXz-arK7RGMobIkvUvVYSfTjkwd1HU)

Hi @ehartford 
Can you share the model stub of the deepseek model you're trying to run?

**Comment by HelloCard** [comment] 2024-12-19 15:17
I use the following script to quantize the model to W8A8 format. I have quantized more than a dozen models. Until now, when I use the latest 0.3.1 version to quantize the model on two 4090Ds, the GPU performance is still used one by one: for a 40-layer model, GPU1 is fully loaded when compressing layer1~20, and GPU2 is fully loaded when compressing layer21~40.
Is this normal?
```
from llmcompressor.transformers import SparseAutoModelForCausalLM
from transformers import AutoTokenizer
import torch
MODEL_ID = "/root/autodl-tmp/phi-4-abliterated"
model = SparseAutoModelForCausalLM.from_pretrained(
    MODEL_ID, device_map="auto", torch_dtype="auto",
)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

from datasets import load_dataset

NUM_CALIBRATION_SAMPLES = 2048
MAX_SEQUENCE_LENGTH = 2048

# Load and preprocess the dataset
ds = load_dataset("/root/autodl-tmp/ultrachat_2k", split="train_sft")
ds = ds.shuffle(seed=42).select(range(NUM_CALIBRATION_SAMPLES))

def preprocess(example):
    return {"text": tokenizer.apply_chat_template(example["messages"], tokenize=False)}
ds = ds.map(preprocess)

def tokenize(sample):
    return tokenizer(sample["text"], padding=False, max_length=MAX_SEQUENCE_LENGTH, truncation=True, add_special_tokens=False)
ds = ds.map(tokenize, remove_columns=ds.column_names)


from llmcompressor.transformers import oneshot
from llmcompressor.modifiers.quantization import GPTQModifier
from llmcompressor.modifiers.smoothquant import SmoothQuantModifier

# Configure the quantization algorithms
recipe = """
DEFAULT_stage:
  DEFAULT_modifiers:
    SmoothQuantModifier:
      smoothing_strength: 0.85
      mappings:
      - - ['re:.*qkv_proj']
        - re:.*input_layernorm
      - - ['re:.*gate_up_proj']
        - re:.*post_attention_layernorm
    GPTQModifier:
      sequential_update: false
      targets: Linear
      scheme: W8A8
"""

# Apply quantization
oneshot(
    model=model,
    dataset=ds,
    recipe=recipe,
    max_seq_length=MAX_SEQUENCE_LENGTH,
    num_calibration_samples=NUM_CALIBRATION_SAMPLES,
)

# Save the compressed model
SAVE_DIR = MODEL_ID.split("/")[1] + "-W8A8-Dynamic-Per-Token"
model.save_pretrained(SAVE_DIR, save_compressed=True)
tokenizer.save_pretrained(SAVE_DIR)
```
```
root@autodl-container-70e24d854c-600141ef:~/autodl-tmp# nvidia-smi
Thu Dec 19 23:17:23 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.120                Driver Version: 550.120        CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090 D      On  |   00000000:16:00.0 Off |                  Off |
| 31%   47C    P2            281W /  425W |   15617MiB /  24564MiB |     95%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090 D      On  |   00000000:A8:00.0 Off |                  Off |
| 30%   27C    P8             25W /  425W |   15129MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
+-----------------------------------------------------------------------------------------+
```

**Comment by ehartford** [comment] 2024-12-19 15:37
I'm trying specifically Deepseek-V2.5-1210 on 8x H100

**Comment by HelloCard** [comment] 2024-12-24 16:54
@dsikka 
I understand. This means that this situation is caused by the GPTQ algorithm and is normal in llm-compressor GPTQ quantization?

**Comment by moonlightian** [comment] 2024-12-25 07:54
> Hi @moonlightian We ran the experiment on our end with both 4 x A100 and 1 x A100. With 4 x A100, we expect about 6-7 hours of time. With 1 x A100, we expect about 12-13 hours.
> 
> Can you try updating to the latest compressed-tensors/llmcompressor and ensure accelerate is installed? After that, can you try passing in the following device_map, when loading the model?
> 
> ```python
> from llmcompressor.transformers.compression.helpers import calculate_offload_device_map
> device_map = calculate_offload_device_map(
>     MODEL_ID, num_gpus=n_gpus, reserve_for_hessians=True, torch_dtype="auto"
> )
> ```
> 
> Once the model is loaded, can you confirm what the following output looks like?
> 
> ```
> for m in model.model.layers:
>     print(m.self_attn.q_proj.weight.device)
> ```

Yeah, thank you for your response，I tried with the latest compressed-tensors and make shm-size bigger for my container and finally I got similar results as you offered. And I could say it is acceptable for me with about 6 hours' cost. Thank you again~

**Comment by dsikka** [comment] 2024-12-25 12:51
> @dsikka 
> 
> I understand. This means that this situation is caused by the GPTQ algorithm and is normal in llm-compressor GPTQ quantization?

Yes. Having more GPUs allows more of the model to be loaded and calibrated using the GPUs but a byproduct of the layer-by-layer nature of the implementation is that not all layers are active at once.

**Comment by dsikka** [comment] 2024-12-25 12:52
@moonlightian Awesome! Closing this for now. Please let me know if you run into other issues

**Closed** 2024-12-25 12:52 UTC
Labels: enhancement
