### ISSUE TITLE
Encounter error "No modifier of type 'SparseGPTModifier' found" when upgrading to 0.3.0

### ISSUE THREAD

**Issue by jiangjiadi** [vllm-project/llm-compressor#925] opened 2024-11-19 09:03 UTC
**Describe the bug**
When I run `examples/quantization_2of4_sparse_w4a16/llama7b_sparse_w4a16.py`, I encounter the error "No modifier of type 'SparseGPTModifier' found". The version I used is 0.3.0. And I also found version 0.2.0 works well.

**Comment by dsikka** [comment] 2024-11-19 16:04
Hi @jiangjiadi - we are not able to reproduce this issue on our end. Can you confirm you're starting from a clean environment and confirm what updates, if any, have been made to the example recipe?

**Comment by robertgshaw2-neuralmagic** [comment] 2024-12-06 19:01
Closing given unable to reproduce. Please reopen if the problem persists.

**Closed by robertgshaw2-neuralmagic** 2024-12-06 19:01 UTC
Labels: bug
